Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Max: 250
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
HashSyntax:
  Enabled: false
NumericLiterals:
  Enabled: false
